LOG_LEVEL = "debug"
ETH_CHAIN_ID = 3
MIN_OUTGOING_CONFIRMATIONS = 2
LINK_CONTRACT_ADDRESS = "0x20fe562d797a42dcb3399062ae9546cd06f63280"
ALLOW_ORIGINS = "*"
TLS_CERT_PATH = "/chainlink/tls/server.crt"
TLS_KEY_PATH = "/chainlink/tls/server.key"
DATABASE_TIMEOUT = 0
DATABASE_URL = "postgresql://YOUR_DB_USER:YOUR_USER_PASS@AMAZON_DB_ADDRESS:AMAZON_DB_PORT/DB_NAME"
ETH_URL = "YOU_SHOULD_CHANGE_THIS"